language: node_js
node_js:
  - '12'
git: 
  depth: 3
script: npm run build
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  keep-history: true
  local-dir: dist/
  target-branch: now
  commit_message: "Deploy Release"
  on:
    branch: master